### PR TITLE
Default instock variant

### PR DESCRIPTION
**Pull request by sbounmy**
hi @citrus,

This PR add a new configuration option : default_instock_variant.

I've updated the readme with the different configuration options.

Specs and cucumber features are green :beer:

Let me know if you have any questions.

Stephane.

### CODE REVIEW

**Comment by citrus** [comment]
Excellent work Stephane! Thanks so much!!!

**Comment by citrus** [comment]
Quick question.. can I remove the ruby-debug dependency? Or at least not require it when running tests on travis? 

Thanks :)

-Spencer

**Comment by sbounmy** [comment]
ofc you can remove it, I couldn't run the test either, I had to comment them out.

Stephane

**Comment by citrus** [comment]
Right on.. removing!

**Comment by citrus** [comment]
how 'bout `launchy`?

**Comment by sbounmy** [comment]
I need that one ^^

**Comment by citrus** [comment]
mmmk no problem :)

**Pull request merged**
