### PR TITLE
spree 1.1 support

### LINKED ISSUE #27: 1.1.x Compatibility
We need to make spree_variant_options Compatible with Spree 1.1.x....

I'm working on this today but thought I'd open an issue to save someone from doing this as well.

-Spencer

/cc @sbounmy

### PR DESCRIPTION
**Pull request by sbounmy**
Hello @citrus,

Everything is green :beer: fixed #27

### CODE REVIEW

**Comment by citrus** [comment]
@sbounmy - Thanks so much, you're the man!

**Comment by citrus** [comment]
Hmmm.. still failing on Travis. Looks like we need to remove the debugger dep for < 1.9, but on > 1.9 I'm not sure why. Any ideas?

http://travis-ci.org/#!/citrus/spree_variant_options/builds/1526863

**Comment by sbounmy** [comment]
Travis ci advise to remove debugger. maybe we could include it in gemfile only for development : http://about.travis-ci.org/docs/user/languages/ruby/

**Comment by sbounmy** [comment]
weird that this is failing on travis… I will investigate asap

**Comment by citrus** [comment]
I removed debugger in d9c1ad71021ecb198e099fbd02bfd02902a276c6 but it's still failing :(  The breakage seems to be related to `track_inventory_levels` and `default_instock`.

Let me know if you find anything!

Thanks,

-Spencer

**Comment by sbounmy** [comment]
@citrus,

it is really weird, I tried on my laptop:
- use new gemset with ruby 1.9.3
- bundle install
- bundle exec dummier
- rake

and it's green...
Maybe it could come from xvfb ? Looks like this is the only difference with what I'm running locally.
I am trying to install xvfb but without success..

If you have some spare time could you run the specs locally aswell ? I keep you in touch..

**Comment by citrus** [comment]
@sbounmy I've been getting all green locally too... wtf! 

I think you're right as it must be xvfb...

**Pull request merged**
